---
- name: first play
  hosts: all
  tasks:
    - name: create a new file
      file:
        path: /tmp/foo.conf
        mode: 0664
        owner: automation
        state: touch
    
    - name: create groups
      import_tasks: group_tasks.yml