---
- name: Reusing Playbook
  hosts: all
  tasks:
    - name: Reboot servers
      reboot:
        msg: Server is rebooting
    
- name: Run first playbook (1_create_file.yml)
  import_playbook: 1_create_file.yml