---
- name: Working with variables
  hosts: all
  vars_files: my_vars.yml
  
  tasks:
    - name: Show me favorite color
      debug:
        msg: My favorite color is {{ fav_color }}
      tags: color

    - name: Show me all ports
      debug:
        msg: The ports are {{ port_nums }}
      tags: port_nums

    # Using an INDEX position to access the specific element 
    - name: Show me a specific port
      debug:
        msg: The ports are {{ port_nums[4] }}
      tags: spec_port
    
    - name: Show 2nd port in the port_nums
      debug:
        msg: SSH port is {{ port_nums[2] }}
      tags: ssh
    
    - name: Show the uid of bob
      debug:
        msg: The UID of Bob is {{ users.bob.uid }}
      tags: uid