---
- name: Greet the user
  hosts: node2
  vars_prompt:
    - name: username
      prompt: Qual é seu nome?
      # private yes, hidden what you type. So can be used for password when needed to input data.
      private: no
  
  tasks:
  - name: Greet the user
    debug:
      msg: Hello {{ username }}