---
- name: Adding custom facts in node01
  hosts: node01
  tasks:
    - name: Create facts.d directory
      file:
        path: /etc/ansible/facts.d
        owner: centos
        mode: 775
        state: directory
      tags: directory
    
    - name: Copy cool.facts to the facts.d directory
      copy: 
        src: cool.fact
        dest: /etc/ansible/facts.d
      tags: file

    - name: Node OS Distribution
      debug:
        msg: The octops is {{ ansible_local.cool.fun.octupus }}
      tags: facts