---
- name: Regsiter Playbook
  hosts: node03
  tasks:
    - name: Run command
      command: uptime
      register: server_uptime
      tags: uptime
    
    - name: Inspect server_uptime variable
      debug:
        var: server_uptime 
    
    - name: Show the server uptime
      debug:
        msg: "{{ server_uptime.stdout}}"