---
- name: Print list
  hosts: node01
  vars:
    vuln_ports: [21,22,23,25,69,137,139,445,53,443,80,8080,8443]
  
  tasks:
    - name: Show the Most Vulnerable Ports to Check When Pentesting
      debug:
        msg: "{{ item }}"
      loop: "{{ vuln_ports }}"