---
- name: Add multiples users
  hosts: node04
  vars:
    dbusers:
      - username: brad
        pass: pass1
      - username: jhon
        pass: pass2
      - username: jason
        pass: pass3 
  tasks:
    - name:  Add users
      user:
        name: "{{ item.username }}"
        password: "{{ item.pass | password_hash('sha512') }}"
      loop: "{{dbusers}}"