---
- name: Using when with facts
  hosts: nodes
  tasks:
    - name: Looking for specific distro
      debug:
        msg: "This is an Centos server"
      when: ansible_facts['distribution'] == "CentOS" 
    
    - name: Show the distro servers
      debug:
        msg: The distro is {{ ansible_facts.distribution }}
      tags: distro