---
- name: Dectect CentOS server
  hosts: nodes
  
  tasks:
  - name: Save the contents of /etc/os-release
    command: cat /etc/os-release
    register: os_release

  - name: Detect CentOS server
    debug: 
      msg: "Running CentOS ..."
    when: os_release.stdout.find('CentOS') != -1