---
- name: Install and start apache
  hosts: web    
  tasks:
    - name: Install and start apache
      block:
        # Install http package 
        - name: Install httpd
          yum: 
            name: httpd
            state: latest
          tags: httpd

        # Start and enable like command "systemctl start httpd && system enable httpd"
        - name: Start and enable
          service: 
            name: httpd
            state: started
            enabled: yes
    - name: This task is outside the block
      debug:
        msg: "I am outside the block now ..."
