---
- name:  Handling error
  hosts: web
  tasks:
    - name: Handling error exemplo 
      block:
        - name: run a command
          command: uptime

        - name: run a bad command
          command: blablabla
          ignore_errors: yes

        - name: This tasks is not run
          debug: 
            msg: "I never run because the above tasks fail"

      rescue:
        - name: Run when the bloc failed
          debug:
            msg: "Block failed, let's try to fix it here"