---
- name: "Show the numbers from 20 to 40"
  hosts: node01
  tasks:
    - name: "Show the numbers from 20 to 40"
      debug:
        msg: "Show the numbers from 20 to 40"
      loop: "{{ range(20,40) | list }}"
      loop_control:
        pause: 2

    - name: "You got it"
      debug: 
        msg: "You got it numbers from 20 to 40"