---
- name: Install packates depends on distro
  hosts: nodes
  tasks:
    - name: Looking for distro CentOS 7 
      debug:
        msg: "CentOS 7 found on this node" 
      when: ansible_facts['distribution'] == "CentOS" and
            ansible_facts['distribution_major_version'] == "7"
      tags: centos

    - name: install nmap package only on CentOS 7
      package:
        name: 
          - nmap
        state: present
      tags: nmap
  
    - name: Looking for distro Ubuntu 
      debug:
        msg: "Ubuntu found on this node" 
      when: ansible_facts['distribution'] == "Ubuntu" and
            ansible_facts['distribution_major_version'] == "20.04"
      tags: ubuntu

    - name: install httpd package only on Ubuntu servers
      package:
        name: httpd
        state: latest